# -*- coding: utf-8 -*-
"""app1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d6NxtIAkts3WHgCWOOo0szsDwskik-3
"""

import streamlit as st
import tensorflow as tf
import numpy as np

from PIL import Image


# Load model

model = tf.keras.models.load_model(
    "cifar10_model.keras"
)


# CIFAR-10 classes

class_names = [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck"
]


# App title

st.title("CIFAR-10 Image Classifier")

st.write(
    "Upload an image and the AI model will "
    "predict its CIFAR-10 category."
)


# Upload image

uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)


if uploaded_file is not None:

    image = Image.open(
        uploaded_file
    ).convert("RGB")

    st.image(
        image,
        caption="Uploaded Image"
    )


    # Resize

    processed_image = image.resize(
        (32, 32)
    )


    # Convert to numpy

    processed_image = np.array(
        processed_image
    )


    # Normalize

    processed_image = (
        processed_image.astype("float32")
        / 255.0
    )


    # Add batch dimension

    processed_image = np.expand_dims(
        processed_image,
        axis=0
    )


    # Prediction

    prediction = model.predict(
        processed_image
    )


    predicted_class = np.argmax(
        prediction
    )

    confidence = np.max(
        prediction
    ) * 100


    # Results

    st.subheader("Prediction")

    st.success(
        class_names[predicted_class]
    )

    st.write(
        f"Confidence: {confidence:.2f}%"
    )